import { reactive } from "vue";

export const staffList = reactive([
  {
    id: 1,
    userName: "Theresa Webb",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 2,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559999",
    credits: 25,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 3,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 10,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 4,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 5,
    tokens: 0,
    avatar: "",
    userStatus: "BLOCKED",
    password: "888",
  },
  {
    id: 5,
    userName: "Wade Warren",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 6,
    userName: "Cameron Williamson",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 7,
    userName: "Jerome Bell",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 8,
    tokens: 0,
    avatar: "",
    userStatus: "BLOCKED",
    password: "888",
  },
  {
    id: 8,
    userName: "Bessie Cooper",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 9,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 12,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 10,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 1,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 11,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 12,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 3,
    tokens: 0,
    avatar: "",
    userStatus: "BLOCKED",
    password: "888",
  },

  {
    id: 13,
    userName: "Theresa Webb",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 14,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 22,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 15,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 16,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 777,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 17,
    userName: "Wade Warren",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 90,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 18,
    userName: "Wade First",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 7,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 19,
    userName: "Cameron Williamson",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 7,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 20,
    userName: "Jerome Bell",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 43,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 21,
    userName: "Bessie Cooper",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 234,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 22,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 1,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 23,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    tokens: 0,
    avatar: "",
    userStatus: "BLOCKED",
    password: "888",
  },
  {
    id: 24,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 258,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },
  {
    id: 25,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 660,
    tokens: 0,
    avatar: "",
    userStatus: "ACTIVE",
    password: "888",
  },

  {
    id: 100,
    userName: "John Doe",
    email: "admin1@test",
    phone: "+71111111111",
    credits: 22,
    tokens: 33,
    avater: "",
    userStatus: "ACTIVE",
    password: "111",
  },
  {
    id: 101,
    userName: "Darrell Steward",
    email: "admin2@test",
    phone: "+72222222222",
    credits: 11,
    tokens: 55,
    avater: "",
    userStatus: "ACTIVE",
    password: "222",
  },
]);
