import { reactive } from "vue";

export const staffList = reactive([
  {
    id: 1,
    userName: "Theresa Webb",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 2,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 25,
    userStatus: "ACTIVE",
  },
  {
    id: 3,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 10,
    userStatus: "ACTIVE",
  },
  {
    id: 4,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 5,
    userStatus: "BLOCKED",
  },
  {
    id: 5,
    userName: "Wade Warren",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 6,
    userName: "Cameron Williamson",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 7,
    userName: "Jerome Bell",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 8,
    userStatus: "BLOCKED",
  },
  {
    id: 8,
    userName: "Bessie Cooper",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 9,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 12,
    userStatus: "ACTIVE",
  },
  {
    id: 10,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 1,
    userStatus: "ACTIVE",
  },
  {
    id: 11,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 12,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 3,
    userStatus: "BLOCKED",
  },

  {
    id: 13,
    userName: "Theresa Webb",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 14,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 22,
    userStatus: "ACTIVE",
  },
  {
    id: 15,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "ACTIVE",
  },
  {
    id: 16,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 777,
    userStatus: "ACTIVE",
  },
  {
    id: 17,
    userName: "Wade Warren",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 90,
    userStatus: "ACTIVE",
  },
  {
    id: 18,
    userName: "Wade First",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 7,
    userStatus: "ACTIVE",
  },
  {
    id: 19,
    userName: "Cameron Williamson",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 7,
    userStatus: "ACTIVE",
  },
  {
    id: 20,
    userName: "Jerome Bell",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 43,
    userStatus: "ACTIVE",
  },
  {
    id: 21,
    userName: "Bessie Cooper",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 234,
    userStatus: "ACTIVE",
  },
  {
    id: 22,
    userName: "Darrell Steward",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 1,
    userStatus: "ACTIVE",
  },
  {
    id: 23,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 0,
    userStatus: "BLOCKED",
  },
  {
    id: 24,
    userName: "Marvin McKinney",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 258,
    userStatus: "ACTIVE",
  },
  {
    id: 25,
    userName: "Brooklyn Simmons",
    email: "name@domian.com",
    phone: "+497074559490",
    credits: 660,
    userStatus: "ACTIVE",
  },
]);
